### ISSUE TITLE
Django 4.2: psycopg v3 support

### ISSUE THREAD

**Issue by adamchainz** [Opus10/django-pgtrigger#119]
I'm testing a project with the Django 4.2 beta. I tried to use the new [psycopg 3 support](https://docs.djangoproject.com/en/4.2/releases/4.2/#psycopg-3-support) by installing `pscyopg` and uninstalling `psycopg2`. This lead to an import error in `django-pgtrigger`:

```
  File "/opt/venv/lib/python3.10/site-packages/pgtrigger/contrib.py", line 5, in <module>
    from pgtrigger import core
  File "/opt/venv/lib/python3.10/site-packages/pgtrigger/core.py", line 12, in <module>
    import psycopg2.extensions
ModuleNotFoundError: No module named 'psycopg2'
```

It would be good to test with Django 4.2 and psycopg 3, adapting as necessary.

**Comment by carlosdorneles-mb** [comment]
Are there any plans to add django 4.2 + psycopg 3 compatibility?

**Comment by adamchainz** [comment]
There's discussion in #120. Short answer is: Django 4.2 compatibility is easy, it's already compatible, but psycopg3 needs a redesign of the library.

**Comment by adam006** [comment]
bump, we are also running into an issue wish needing to upgrade this as well at Advantage

**Comment by wesleykendall** [comment]
django-pgrigger 4.7 is now tested against python 3.11, postgres 15, Django 4.2, and psycopg3. Along with updating the test suite, I also had a few others test it out within the context of their projects.

Should be good to go! @adamchainz I added you as a `Co-authored-by` on https://github.com/Opus10/django-pgtrigger/pull/124. Thanks for the help! I am going to respond to the discussion in the PR about the SQL variable injection since I have a plan to support both use cases
