### ISSUE TITLE
Add support for unmanaged models

### ISSUE THREAD

**Issue by arnav13081994** [Opus10/django-pgtrigger#121]
Great Library! One useful feature would be to add the ability to add triggers using `django-pgtrigger` on `unmanaged` models. I have not had any success with that which led me to assume that it is not possible. Unless I made mistake?

**Comment by wesleykendall** [comment]
pgtrigger uses Django's migration system by default for triggers. Since unmanaged models aren't migrated, triggers will also not appear in the migrations for these models.

Turning off the migration integration may help your use case, but I'd recommend manually installing the triggers in a data migration.

```
import pgtrigger

pgtrigger.install("app.Model:trigger_name")
```

If it can't find the trigger, you may need to manually register it to the model in your apps.py:

```
import pgtrigger


pgtrigger.register(MyTrigger())(MyModel)
```

Django `constraints`, `indexes`, and other `Meta` options are not support on unmanaged models, so I'm not planning to make `triggers` be a special case. They will have to be manually installed like other things on unmanaged models.

Hope you're able to work around this for your use case
