### ISSUE TITLE
Clarification on trigger name length limit

### ISSUE THREAD

**Issue by sshivananda** [Opus10/django-pgtrigger#30]
[https://github.com/Opus10/django-pgtrigger/blob/master/pgtrigger/core.py#L427](https://github.com/Opus10/django-pgtrigger/blob/master/pgtrigger/core.py#L427) limits trigger names to 43 chars. I am assuming the `pgtrigger_` prefix adds another 10 chars , and 5 more for the hash suffix - bringing the total to 58 chars.

[Stackoverflow post on max name suggests](https://stackoverflow.com/questions/8213127/maximum-characters-in-labels-table-names-columns-etc ) that 63 char names are allowed.

Can we add comments in the code around the 43 character limit ? (Happy to submit a PR)

**Comment by wesleykendall** [comment]
@sshivananda I believe the 43 char limit is because of historical reasons when the library named triggers differently. There is one more `_` added to the name https://github.com/Opus10/django-pgtrigger/blob/master/pgtrigger/core.py#L439, so I think we can get away with allowing 4 more chars in the name. I will check it out more and at least add comments to it. Thanks!

**Comment by wesleykendall** [comment]
I went ahead and extended the max length to 47 chars in https://github.com/Opus10/django-pgtrigger/pull/33. I wrote a test to verify that the generated identifier goes to 64 chars when the trigger name is too long.

Ideally the user-defined name length wouldn't matter since you can always hash the latter-part of it, similar to Django. This is just a bit more involved though since I should also do checking to verify there are no collisions in other aspects of the code. May revisit this later if the 47 char limit is too annoying.

Also I learned today that if you create a trigger with > 64 chars as the name, postgres doesn't complain. It just silently truncates it. In the PR, I also do another sanity check on the generated trigger ID because of this.
