### ISSUE TITLE
Feature request: Allow just referencing built-in procedures

### ISSUE THREAD

**Issue by ralokt** [Opus10/django-pgtrigger#38]
I'm trying to use `django-pgtrigger` to apply `tsvector_update_trigger` [1], a built-in procedure that takes parameters.

Doing so from another procedure is cumbersome if even possible, as it expects me to pass column names for the current table, which doesn't work:

```
CALL tsvector_update_trigger(
    this_column_name_exists_but_is_not_found,
    'pg_catalog.english',
    this_column_name_is_also_not_found
);
```

(Disclaimer: I'm aware that I might be missing something here, I'm new to PL/pgSQL, but it seems to me like these procedures expect some kind of "current table" context that is absent when called this way).

So, as far as I can tell, currently, I have to subclass `Trigger` to support calling a procedure with arguments, or replicate the logic of `tsvector_update_trigger` in my custom func. Both mean writing and maintaining PL/pgSQL, which is precisely what I'm trying to avoid by using `django-pgtrigger` (along with any significant SQL).

It would be nice if triggers could also support a `procedure` argument that could be specified instead of `func` and used like
```python
pgtrigger.Trigger(
    (...),
    procedure="tsvector_update_trigger(tsv, 'pg_catalog.english', text);",
)
```

In this case, no new procedure would be generated. Instead, that procedure call would be used in its place, producing output like
```
(...)
    FOR EACH ROW EXECUTE FUNCTION
        tsvector_update_trigger(tsv, 'pg_catalog.english', text);
(...)
```

[1] https://www.postgresql.org/docs/9.5/textsearch-features.html#TEXTSEARCH-UPDATE-TRIGGERS

**Comment by mnamegaurav** [comment]
I am also looking for a similar feature, I am implementing Full Text Search in Django, but want to increase the performance by using `tsvector_update_trigger` to automatically update the search field vector value in the database. I would love to see such a feature in this library.

**Comment by Mariownyou** [comment]
the same problem

**Comment by wesleykendall** [comment]
@ralokt @mnamegaurav @Mariownyou thanks for letting me know about this use case. I'm not totally wrapping my head around how this isn't currently possible in pgtrigger, but let me write a test case for it using this exact procedure. If it's not possible, I'll integrate it into the library. If it is, I'll add an example to the trigger cookbook in the docs

**Comment by Mariownyou** [comment]
Thanks for the quick reply.That would be very helpful👍🏼

**Comment by wesleykendall** [comment]
@ralokt @Mariownyou @mnamegaurav 

I decided to support this as a first-class trigger in ``django-pgtrigger`` after I found that the [Django docs](https://docs.djangoproject.com/en/4.0/ref/contrib/postgres/search/#searchvectorfield) simply point people to the Postgres docs to make a trigger for this.

Now you can use `pgtrigger.UpdateSearchVector`. It follows the same definition example as provided in the [Postgres docs](https://www.postgresql.org/docs/current/textsearch-features.html#TEXTSEARCH-UPDATE-TRIGGERS). I.e. it will make a trigger that updates the search field on insert or updates of relevant fields. It uses the built-in `tsvector_update_trigger` function and references it directly in the trigger.

For example, this is a trigger that keeps a search field vector updated from two columns:

```
class DocumentModel(models.Model):
    search_vector = SearchVectorField()
    title = models.CharField(max_length=128)
    body = models.TextField()

    class Meta:
        triggers = [
            pgtrigger.UpdateSearchVector(
                name="add_title_and_body_to_vector",
                vector_field="search_vector",
                document_fields=["title", "body"],
            )
        ]
```

I didn't add first-class support for directly referencing functions just yet since I'm not sure how widespread of a use-case this is. It also interferes with `pgtrigger.ignore` functionality. I did, however, update the trigger rendering to make it easier for someone to do it in a derived trigger class though, and you can take a look at the `pgtrigger.UpdateSearchVector` code to see how.

Hope this helps! I will open a PR for the official Django docs and see if they're interested in pointing users to this trigger for keeping ``SearchVectorField`` updated.

If you have any other use cases, such as doing `setweight` in triggers, I'd be interested to hear more. Similarly let me know if you don't think that the built-in trigger will support your use case. I'm going to go ahead and release this tonight with other things, and I'm happy to re-open the issue or do follow-up PRs

**Comment by wesleykendall** [comment]
Released in 3.4! There's an [example in the docs](https://django-pgtrigger.readthedocs.io/en/latest/cookbook.html#keeping-a-search-vector-updated) on how to use it

**Comment by Mariownyou** [comment]
Thanks for the quick release, I'll go check it out right now. I'll let you know if anything goes wrong. thanks again

**Comment by ralokt** [comment]
This is awesome! Yeah, when I made this issue I hadn't dug too deep yet and didn't realize that `pgtrigger.ignore` would be broken by the suggested fix - seems practical to just support this very common use case instead. Thanks a lot!
