### ISSUE TITLE
Before Insert trigger still violates not-null constraint

### ISSUE THREAD

**Issue by apkallum** [Opus10/django-pgtrigger#56]
Hello, I'm using pg-trigger to update a column in Table 2 (Workspace) before I insert a row in Table 1 (Task):
```
@pgtrigger.register(
    pgtrigger.Trigger(
        name="increment_workspace_highest_task_number",
        when=pgtrigger.Before,
        operation=pgtrigger.Insert,
        func="""
        DECLARE 
        highest_number  INTEGER;
        BEGIN
            SELECT workspace_workspace.highest_task_number INTO highest_number
            FROM workspace_workspace
            WHERE workspace_workspace.id = NEW.workspace_id;
            UPDATE "workspace_workspace" AS workspace
            SET "highest_task_number" = highest_number + 1
            FROM workspace_workspace
            WHERE workspace.id = NEW.workspace_id;
            NEW.number = highest_number + 1;
            RETURN NEW;
        END;""",
    )
)
```   
I'm doing this operation on a Task table (model) that has a number field (column). I get the following error: 
```
psycopg2.errors.NotNullViolation: null value in column "number" violates not-null constraint
```
Is there a way to bypass that error other than making the column nullable?

**Comment by wesleykendall** [comment]
A few things to note here.

1. It seems like your trigger definition may not be compatible with django-pgtrigger. The `func` attribute is automatically inserted between a `BEGIN` and `END`, and the `declare` attribute of the trigger can be used to declare variables like your declaration. [See the anatomy of a trigger in the docs](https://django-pgtrigger.readthedocs.io/en/latest/basics.html#the-anatomy-of-a-trigger)
2.   I assume what's happening is that `highest_number` has a `null` value inserted into it instead of a `0`. I don't know the exact syntax, but you're probably going to want to do a `COALESCE` somewhere to return a `0` instead of a `null`

**Comment by wesleykendall** [comment]
I believe I've addressed the issue, but feel free to re-open if I haven't
