### ISSUE TITLE
Usage of built in SoftDelete

### ISSUE THREAD

**Issue by jzmiller1** [Opus10/django-pgtrigger#70]
I've been enjoying the 3.x releases!

I am currently using the built in SoftDelete and was curious if there was a best practices or suggested method for overriding the trigger through Django and doing hard deletes?

Also how much are the built in Triggers like SoftDelete intended to be examples vs a set of "batteries included" tools?  For example, I am adding the delete time via SoftDelete and was wondering if things like this would be something that should be submitted back to the project with a PR with relevant tests and doc updates?

```python
class SoftDeleteWithDatetime(Trigger):
    """Sets a field to a value when a delete happens.

    Supply the trigger with the "field" that will be set
    upon deletion and the "value" to which it should be set.
    The "value" defaults to ``False``.

    .. note::

        This trigger currently only supports nullable ``BooleanField``,
        ``CharField``, and ``IntField`` fields.
    """

    when = Before
    operation = Delete
    field = None
    value = False

    def __init__(self, *, name=None, condition=None, field=None, value=_unset, field_datetime=None):
        self.field_datetime = field_datetime
        self.field = field or self.field
        self.value = value if value is not _unset else self.value

        if not self.field:  # pragma: no cover
            raise ValueError('Must provide "field" for soft delete')

        super().__init__(name=name, condition=condition)

    def get_func(self, model):
        soft_field = model._meta.get_field(self.field).column
        soft_field_datetime = model._meta.get_field(self.field_datetime).column
        pk_col = model._meta.pk.column

        def _render_value():
            if self.value is None:
                return 'NULL'
            elif isinstance(self.value, str):
                return f"'{self.value}'"
            else:
                return str(self.value)

        if self.field_datetime is not None:
            return f'''
            UPDATE {_quote(model._meta.db_table)}
            SET
            {soft_field} = {_render_value()},
            {soft_field_datetime} = NOW()
            WHERE {_quote(pk_col)} = OLD.{_quote(pk_col)};
            RETURN NULL;
        '''

        return f'''
            UPDATE {_quote(model._meta.db_table)}
            SET {soft_field} = {_render_value()}
            WHERE {_quote(pk_col)} = OLD.{_quote(pk_col)};
            RETURN NULL;
        '''

```

**Comment by wesleykendall** [comment]
@jzmiller1 thanks for your feedback.

To answer your questions:

1. The best practice for ignoring the trigger in your application so that you can do a hard delete is using `pgtrigger.ignore`. See [this section of the docs](https://django-pgtrigger.readthedocs.io/en/latest/ignoring_triggers.html) for more details.
2. pgtrigger is intended to include a set of "batteries included" tools for some very common use cases. I'm open to extending the default triggers to support more use cases or adding other default triggers. I believe there is a case for adding triggers that update timestamps on events.

Your use case can be solved by using two different trigger definitions:

```
class SoftDelete(models.Model):
    is_active = models.BooleanField(default=True)
    deleted_at = models.DateTimeField(null=True)

    class Meta:
        triggers = [
            pgtrigger.SoftDelete(name='soft_delete', field='is_active'),
            pgtrigger.Trigger(
                name='set_deleted_at',
                when=pgtrigger.Before,
                operation=pgtrigger.Update,
                func="NEW.deleted_at = NOW(); RETURN NEW;",
                condition=pgtrigger.Q(old__is_active=True, new__is_active=False)
            )
        ]
```

In the above, the `deleted_at` time is set whenever `is_active` changes, whether it is the soft delete trigger OR a user that's manually setting the `is_active` flag. This is in contrast to baking it into the soft delete trigger, which only fires when you try to actually delete the model.

Hope that helps! Let me know if you have any issues, otherwise I will close this (FYI I tested out the trigger above and it worked for me)

**Comment by jzmiller1** [comment]
Thanks for the tips!

For some reason I was too focused on having a single trigger and missed the idea of just having another trigger set the time. Thanks, that is a better approach.
